# Generated by Django 4.2.2 on 2023-07-16 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_role_privileges'),
        ('accounts', '0006_account_is_deleted_review_is_deleted'),
    ]

    operations = [
    ]
